FourthPillar/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm,password_reset_complete,LoginView
from rest_framework.urlpatterns import format_suffix_patterns




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('feed.urls')),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout/$', auth_views.logout, name='logout'),

]

urlpatterns=format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.conf.urls import url
from . import views


app_name = 'feed'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^keyword/(?P<keyword>\w+)/$', views.FindKeyWordNews.as_view(), name='keyword'),
    url(r'^keyword/$', views.FindKeyWordNews.as_view(), name='keyword'),
    url(r'^news$', views.news, name='news'),
    url(r'^stats$', views.stats, name='stats'),
    url(r'^republic$', views.republic, name='republic'),
    url(r'^ndtv$', views.ndtv, name='ndtv'),
    url(r'^indiatoday$', views.indiatoday, name='indiatoday'),
    url(r'^hindustan$', views.hindustan, name='hindustan'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^signup$', views.SignUpForm.as_view(), name='signup'),
    url(r'^newsAPI/$', views.NewsList.as_view(), name='newsAPI'),

]

feed/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.

class Republic(models.Model):
    headline = models.TextField(null=False)
    link = models.TextField(null=False)
    date = models.DateTimeField(default=timezone.now)
    category = models.TextField(null=True)
    sentiment = models.TextField(null=True)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ["-date"]


class Indiatoday(models.Model):
    headline = models.TextField(null=False)
    link = models.TextField(null=False)
    date = models.DateTimeField(default=timezone.now)
    category = models.TextField(null=True)
    sentiment = models.TextField(null=True)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ["-id"]


class Ndtv(models.Model):
    headline = models.TextField(null=False)
    link = models.TextField(null=False)
    date = models.DateTimeField(default=timezone.now)

    category = models.TextField(null=True)
    sentiment = models.TextField(null=True)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ["-id"]


class Hindustan(models.Model):
    headline = models.TextField(null=False)
    link = models.TextField(null=False)
    date = models.DateTimeField(auto_now_add=True)
    category = models.TextField(null=True)
    sentiment = models.TextField(null=True)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ["-id"]


class Thehindu(models.Model):
    headline = models.TextField(null=False)
    link = models.TextField(null=False)
    date = models.DateTimeField(default=timezone.now)
    category = models.TextField(null=True)
    sentiment = models.TextField(null=True)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ["-id"]


class Zeenews(models.Model):
    headline = models.TextField(null=False)
    link = models.TextField(null=False)
    date = models.DateTimeField(default=timezone.now)
    category = models.TextField(null=True)
    sentiment = models.TextField(null=True)

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ["-id"]


class IndexTop10(models.Model):
    db_keyword = models.TextField(null=False)
    db_frequency = models.PositiveIntegerField(null=False, default=0)

feed/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name','username','email','password1','password2')




class LoginForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email','password1')

feed/views.py
from typing import List
from itertools import chain
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.contrib.auth import login, authenticate
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.views import generic
from .forms import SignUpForm, LoginForm
from .models import Republic, Ndtv, Indiatoday, Hindustan, Thehindu, Zeenews, IndexTop10
import psycopg2
import nltk
from nltk.corpus import stopwords
import string
from nltk.probability import FreqDist
from django.db.models import Q
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import NewsSerializer

headlines = ""

new_stop_words = ['says', 'khan', 'singh', "'s", "''",
                  'to', 'in', 'for', 'on', 'of', '``', 'and', 'the',
                  'a', 'after', '10', "n't", 'man', 'us', 'first', 'day', "'", '’', '‘', 'new', 'vs', 'india', 'top',
                  '...', 'life',
                  'gets', 'back', 'takes', 'rs', 'take'

                  ]


def getHeadLine(headline):
    global headlines
    for title in headline:
        headlines += title.headline


def index(request):
    keyword = []
    keyword_frequency = []
    for key in IndexTop10.objects.all():
        keyword.append(key.db_keyword)
        keyword_frequency.append(key.db_frequency)

    keyword.append("end")
    keyword_frequency.append(0)
    context = {
        "keyword": keyword,
        "keyword_frequency": keyword_frequency,
    }

    return render(request, 'feed/index.html', context)


def news(request):
    republic_headline = Republic.objects.order_by('-id')[0:5]
    indiatoday_headline = Indiatoday.objects.order_by('-id')[0:5]
    hindustan_headline = Hindustan.objects.order_by('-id')[0:5]
    ndtv_headline = Ndtv.objects.order_by('-id')[0:5]
    hindu_headline = Thehindu.objects.order_by('-id')[0:5]
    zeenews_headline = Zeenews.objects.order_by('-id')[0:5]
    context = {
        'republic_headline': republic_headline,
        'ndtv_headline': ndtv_headline,
        'indiatoday_headline': indiatoday_headline,
        'hindustan_headline': hindustan_headline,
        'hindu_headline': hindu_headline,
        'zeenews_headline': zeenews_headline
    }

    return render(request, 'feed/news.html', context)


def republic(request):
    republic_headline = Republic.objects.all().order_by('-id')
    paginator = Paginator(republic_headline, 10)
    page = request.GET.get('page')
    try:
        republic_headline = paginator.page(page)
    except PageNotAnInteger:
        republic_headline = paginator.page(1)
    except EmptyPage:
        republic_headline = paginator.page(paginator.num_pages)

    context = {
        'republic_headline': republic_headline,
    }

    return render(request, 'feed/republic.html', context)


def ndtv(request):
    ndtv_headline = Ndtv.objects.order_by('-id')[0:20]
    context = {
        'ndtv_headline': ndtv_headline,
    }

    return render(request, 'feed/ndtv.html', context)


def indiatoday(request):
    indiatoday_headline = Indiatoday.objects.order_by('-date')[0:20]
    context = {
        'indiatoday_headline': indiatoday_headline,
    }

    return render(request, 'feed/indiatoday.html', context)


def hindustan(request):
    hindustan_headline = Hindustan.objects.order_by('-date')[0:20]
    context = {
        'hindustan_headline': hindustan_headline,
    }

    return render(request, 'feed/hindustan.html', context)


class LoginForm(generic.CreateView):
    print("login")
    form_class = LoginForm
    template_name = "feed/SignUp.html"

    def get(self, request):
        title = "Login to Vote"
        form = self.form_class(None)
        context = {
            "title": title,
            "form": form,

        }
        return render(request, self.template_name, context)

    def Post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                print("try")
                username = request.POST['username']
                username = User.objects.get(email=username).username  # Get username with email
                password = request.POST['password']
                validate_email(username)  # If it's a valid email
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('')

            except:
                print("except")
                UserModel = get_user_model()

                password = request.POST['password']
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('')
        else:
            print(form.errors)


class SignUpForm(generic.CreateView):
    form_class = SignUpForm
    template_name = "feed/SignUp.html"

    def get(self, request):
        title = "SignUp - Save 4th pillar"
        form = self.form_class(None)
        context = {
            "title": title,
            "form": form,
        }
        return render(request, self.template_name, context)

    def post(self, request):

        form = self.form_class(request.POST)
        if form.is_valid():
            print("form valid")
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            form.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('feed:index')
        else:
            print(form.errors)

        return render(request, self.template_name, {'form': form})


def logout_view(request):
    logout(request)
    return index(request)


def stats(request):
    np = Ndtv.objects.filter(sentiment='positive').count()
    nn = Ndtv.objects.filter(sentiment='negative').count()

    rp = Republic.objects.filter(sentiment='positive').count()
    rn = Republic.objects.filter(sentiment='negative').count()

    htp = Hindustan.objects.filter(sentiment='positive').count()
    htn = Hindustan.objects.filter(sentiment='negative').count()

    thp = Thehindu.objects.filter(sentiment='positive').count()
    thn = Thehindu.objects.filter(sentiment='negative').count()

    znp = Zeenews.objects.filter(sentiment='positive').count()
    znn = Zeenews.objects.filter(sentiment='negative').count()

    itp = Indiatoday.objects.filter(sentiment='positive').count()
    itn = Indiatoday.objects.filter(sentiment='negative').count()

    total_positive = np + rp + htp + thp + znp + itp
    total_negative = nn + rn + htn + thn + znn + itn

    lp = [np, rp, htp, thp, znp, itp]
    ln = [nn, rp, htn, thn, znn, itn]

    percentage = (total_positive / (total_positive + total_negative)) * 100

    context = {
        "lp": lp,
        "ln": ln,
        "positive": total_positive,
        "negative": total_negative,
        "percentage": percentage
    }

    return render(request, "feed/stats.html", context)


class FindKeyWordNews(generic.ListView):
    template_name = "feed/keyword.html"

    def get_queryset(self):
        query_list = []
        keyword = self.kwargs.get("keyword")
        if keyword:
            republic = Republic.objects.filter(Q(headline__icontains=keyword)).order_by('-id')
            ndtv = Ndtv.objects.filter(Q(headline__icontains=keyword)).order_by('-id')
            indiatoday = Indiatoday.objects.filter(Q(headline__icontains=keyword)).order_by('-id')
            hindustan = Hindustan.objects.filter(Q(headline__icontains=keyword)).order_by('-id')
            thehindu = Thehindu.objects.filter(Q(headline__icontains=keyword)).order_by('-id')
            zee = Zeenews.objects.filter(Q(headline__icontains=keyword)).order_by('-id')
            query_list = list(chain(republic, ndtv, indiatoday, hindustan, thehindu, zee))

        context = {
            "keyword": keyword,
            "query_list": query_list

        }
        return context


class NewsList(APIView):

    def get(self,arg):
        news = Republic.objects.all()
        serializer = NewsSerializer(news, many=True)

        return Response(serializer.data)

    def post(self):
        pass

feed/templates/feed/base.html
<title>
        {% block title %} Save fourth pillar {% endblock %}
     </title>
{% include "feed/header.html" %}

{% block content%}

{% endblock %}
{% include "feed/footer.html" %}

feed/templates/feed/form_template.html
{% for field in form %}
<div class="row">
    <div class="col l5">
        <p style="text-align:center;"><b>{{field.label_tag}}</b></p>
    </div>
    <div class="col l6">
        {{ field }}
    </div>

    <div class="col l1">
    </div>
</div>
{% endfor %}

feed/templates/feed/header.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fourth Pillar</title>


    <link rel="stylesheet" href="{% static '/css/base.css' %}">
     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- Chart JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

    <!--icon -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">




    <style>

.new-card{
    text-align:left!important;
}


    .sidebar {



}

.sidebar a {

  font-size: 20px;
  color: #0D47A1;
  display: block;
}

.sidebar a:hover {
  color: #1A237E;
  background-color:#8C9EFF;
}
left{
color:#616161;
padding-top:-10px!important;

}
.news-card-bottom{
color:#ff6060;
padding-left:10%;
padding-bottom:5px;
}


        .footer-copyright{
            text-align:center;
        }
        .brand-logo{
            padding-left:100px!important;
            font-weight: bold;
            text-align:center;
        }
        #rank-table{
        border-collapse: collapse!important;
        }

        #rank-table th {
            text-align: left;
            background-color: #4CAF50;
            color: white;

        }
        #rank-table th td{
        height:20px!important;
        }
        img{
            width:80%;
            height:50%;
            margin-left: auto;
	margin-right: auto;
	display: block;
        }
        .left-content-1{
             font-size: 20px;
             padding-left:10px;
        }

    </style>
</head>
<body>
<nav>
        <div class="nav-wrapper">
          <div class="row">
              <div class="col s3">
                   <a href="{% url 'feed:index' %}" class="brand-logo">Save4thPillar</a>
              </div>
              <div class="col s1">

              </div>
              <div class="col s8">
                  <ul id="nav-mobile" class="left hide-on-med-and-down">
                        <li><a href="{% url 'feed:index' %}">Home</a></li>

                        <li><a href="{% url 'feed:stats' %}">Stats</a></li>
                        <li><a href="collapsible.html">Content</a></li>
                  </ul>
              </div>

          </div>
        </div>
    </nav>
<br>

feed/templates/feed/index.html
{% extends "feed/base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <div class="col l2">
             <div class="row">
                <div class="col l12">
                  <div class="row">
                    <div class="input-field col l12">
                      <i class="material-icons prefix">search</i>
                      <input type="text" id="autocomplete-input" class="autocomplete">
                      <label for="autocomplete-input">Search</label>
                    </div>
                  </div>
                    <div class="sidebar">
                      <a href="{% url 'feed:news' %}"><i class="fa fa-fw fa fa-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Top News</a>
                      {% if not user.is_authenticated %}
                        <a href="{% url 'feed:signup' %}"><i class="fa fa-user-plus"></i>&nbsp;&nbsp;&nbsp;&nbsp;Sign Up</a>
                        <a href="{% url 'login' %}"><i class="fa fa-sign-in" ></i></i>&nbsp;&nbsp;&nbsp;&nbsp;Login</a>
                      {% else %}
                        <a href=""><i class="fa fa-fw fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ user.username }}</a>
                        <a href="{% url 'feed:logout' %}"><i class="fa fa-sign-out-alt"></i>&nbsp;&nbsp;&nbsp;&nbsp;logout</a>
                      {% endif %}
                    </div>

                </div>

             </div>
        </div>
        <div class="col l7">
            <div class="card">
                <canvas id="categorychart">
                </canvas>
                <div class="card-content">
                    Analysis of Indian News Media
                </div>
            </div>
            <div class="card">
                <canvas id="keywordchart">
                </canvas>
                 <div class="card-content">
                    Top keyword by indian media
                </div>
            </div>

            <script>
    let keywordchart=document.getElementById('keywordchart').getContext('2d');


    let drawkeywordchart=new Chart(keywordchart,{
        type:'bar',
        data:{
          labels:{{keyword |safe }} ,
          datasets:[{
                        data:{{keyword_frequency}},
                        backgroundColor:['#64B5F6','#E3F2FD','#F06292','#CDDC39','#EA80FC','#FF8A65','#81C784',
                        '#64B5F6','#E3F2FD','#F06292','#CDDC39','#EA80FC','#FF8A65','#81C784',
                        '#64B5F6','#E3F2FD','#F06292'
                        ],

                        borderWidth:3,
                        borderColor:'#777',
                        hoverBorderWidth:6,
                        hoverBorderColor:'#000'
                    }
                  ],

        },




        options:{
                'onClick' : function (evt, item) {
            var keyword = item[0]['_model'].label
            var url = "{% url 'feed:keyword' %}";

            document.location.href = url+keyword;

          },
        }

    });



    let categorychart=document.getElementById('categorychart').getContext('2d');
    let drawcategorychart=new Chart(categorychart,{
        type:'pie',
        data:{
          labels:['Politics','Bollywood','Cricket','Pollution','Population','Unemployment','Child Labour','Price Hike','Corruption','Education'],
          datasets:[{
                        data:[44,20,15,5,2,3,1,2,6,2],
                        backgroundColor:['#64B5F6','#E3F2FD','#F06292','#CDDC39','#EA80FC','#FF8A65','#81C784','#76FF03','#F44336','#00C853'],
                        borderWidth:0,
                        borderColor:'#777',
                        hoverBorderWidth:2,
                        hoverBorderColor:'#000'
                    }
                  ],

        },
        options:{




        }
    });




</script>
















        </div>
        <div class="col l3">
            {% include 'feed/rightsiderank.html' %}
        </div>
    </div>
{% endblock %}

feed/templates/feed/leftsidemenu.html
<div class="row">
                <div class="col l12">
                  <div class="row">
                    <div class="input-field col l12">
                      <i class="material-icons prefix">search</i>
                      <input type="text" id="autocomplete-input" class="autocomplete">
                      <label for="autocomplete-input">Search</label>
                    </div>
                  </div>
                    <div class="sidebar">
                      <a href="{% url 'feed:news' %}"><i class="fa fa-fw fa fa-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Top News</a>
                      <a href="{% url 'feed:news' %}"><i class="fa fa-fw fa-user"></i> &nbsp;&nbsp;&nbsp;Your Profile</a>
                      {% include "registration/login.html" %}
                </div>

</div>
</div>

feed/templates/feed/news.html
{% extends "feed/base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <div class="col l2">
             <div class="row">
                <div class="col 12">
                  <div class="row">
                    <div class="input-field col l12">
                      <i class="material-icons prefix">search</i>
                      <input type="text" id="autocomplete-input" class="autocomplete">
                      <label for="autocomplete-input">Search</label>
                    </div>
                  </div>
                    <div class="sidebar">
                      <a href="#republic"><i class="fa fa-fw fa fa-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Republic</a>
                      <a href="#ndtv"><i class="fa fa-fw fa fa-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;NDTV</a>
                      <a href="#indiatoday"><i class="fa fa-fw fa fa-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;India Today</a>
                      <a href="#thehindu"><i class="fa fa-fw fa fa-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;The Hindu</a>
                      <a href="#hindustantimes"><i class="fa fa-fw fa-list"></i> &nbsp;&nbsp;&nbsp;Hindustan Times</a>
                        {% if not user.is_authenticated %}
            <a href="{% url 'feed:signup' %}"><i class="fa fa-user-plus"></i>&nbsp;&nbsp;&nbsp;&nbsp;Sign Up</a>
            <a href="{% url 'login' %}"><i class="fa fa-sign-in" ></i></i>&nbsp;&nbsp;&nbsp;&nbsp;Login</a>

      {% else %}
          <a href=""></span>&nbsp;{{ user.username }}</a>
          <a href="{% url 'feed:logout' %}"><span class=""></span>&nbsp;logout</a>

        {% endif %}
                    </div>

                </div>
             </div>
        </div>
        <div class="col l7">

            <div class="card" id="republic">
                <br>
                <h6><b>&nbsp;&nbsp;&nbsp;Republic</b></h6>
                <ul class="browser-default">
                    {% for post in republic_headline %}
                    <li><a href="{{ post.link }}"> {{ post.headline }}</a><br>
                    </li>
                    {% endfor %}
                </ul>
                <p class="news-card-bottom"><b><a href="{% url 'feed:republic' %}"> View all coverages from Republic</a></b></p>
            </div>

            <div class="card" id="ndtv">
                <br>
                <h6><b>&nbsp;&nbsp;&nbsp;NDTV</b></h6>
                <ul class="browser-default">
                    {% for post in ndtv_headline %}
                    <li><a href="{{ post.link }}"> {{ post.headline }}</a><br>

                    </li>
                    {% endfor %}
                </ul>
               <p class="news-card-bottom"><b><a href="{% url 'feed:ndtv' %}"> View all coverages from NDTV</a></b></p>
            </div>

            <div class="card" id="indiatoday">
                <br>
                <h6><b>&nbsp;&nbsp;&nbsp;India Today</b></h6>
                <ul class="browser-default">
                    {% for post in indiatoday_headline %}
                    <li><a href="{{ post.link }}"> {{ post.headline }}</a><br>

                    </li>
                    {% endfor %}
                </ul>
                <p class="news-card-bottom"><b><a href="{% url 'feed:indiatoday' %}"> View all coverages from India Today</a></b></p>
            </div>

            <div class="card" id="hindustantimes">
                <br>
                <h6><b>&nbsp;&nbsp;&nbsp;The Hindu</b></h6>
                <ul class="browser-default">
                    {% for post in hindu_headline %}
                    <li><a href="{{ post.link }}"> {{ post.headline }}</a><br>

                    </li>
                    {% endfor %}
                </ul>
               <p class="news-card-bottom"><b><a href="{% url 'feed:hindustan' %}"> View all coverages from Hindustan Time</a></b></p>
            </div>

            <div class="card" id="thehindu">
                <br>
                <h6><b>&nbsp;&nbsp;&nbsp;Zee News</b></h6>
                <ul class="browser-default">
                    {% for post in zeenews_headline %}
                    <li><a href="{{ post.link }}"> {{ post.headline }}</a><br>

                    </li>
                    {% endfor %}
                </ul>
               <p class="news-card-bottom"><b><a href="{% url 'feed:hindustan' %}"> View all coverages from Hindustan Time</a></b></p>
            </div>

            <div class="card" id="zeenews">
                <br>
                <h6><b>&nbsp;&nbsp;&nbsp;Hindustan Times</b></h6>
                <ul class="browser-default">
                    {% for post in hindustan_headline %}
                    <li><a href="{{ post.link }}"> {{ post.headline }}</a><br>

                    </li>
                    {% endfor %}
                </ul>
               <p class="news-card-bottom"><b><a href="{% url 'feed:hindustan' %}"> View all coverages from Hindustan Time</a></b></p>
            </div>



        </div>
        <div class="col l3">

        </div>
    </div>
{% endblock %}

feed/templates/feed/stats.html
{% extends "feed/base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <div class="col l2">
             <div class="row">
                <div class="col 12">
                  <div class="row">
                    <div class="input-field col l12">
                      <i class="material-icons prefix">search</i>
                      <input type="text" id="autocomplete-input" class="autocomplete">
                      <label for="autocomplete-input">Search</label>
                    </div>
                  </div>
                    <div class="sidebar">
                        {% if not user.is_authenticated %}
            <a href=""><i class="fa fa-fw fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;Sign Up</a>
            <a href="{% url 'login' %}"><i class="fa fa-fw fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Login</a>
      {% else %}
          <a href=""><i class="fa fa-fw fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ user.username }}</a>
          <a href="{% url 'feed:logout' %}"><i class="fa fa-fw fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;Logout</a>
        {% endif %}
                    </div>
                </div>
             </div>






        </div>
        <div class="col l7">
        <div class="card">
            <h4>Give star and be the part to save 4th pillar</h4>

                <table>
                    <tr><th>Name</th><th>Rating</th><th>Positive</th><th>Negative</th></tr>
                    <tr><td>1.&nbsp;NDTV</td><td>63.49</td><td>{{ lp.0 }}</td><td>{{ ln.0 }}</td></tr>
                    <tr><td>1.&nbsp;Republic</td><td>50</td><td>{{ lp.1 }}</td><td>{{ ln.1 }}</td></tr>
                     <tr><td>1.&nbsp;Hindustan Time</td><td>69.12</td><td>{{ lp.2 }}</td><td>{{ ln.2 }}</td></tr>
                    <tr><td>1.&nbsp;The Hindu</td><td>92.06</td><td>{{ lp.3 }}</td><td>{{ ln.3 }}</td></tr>
                    <tr><td>1.&nbsp;Aaj Tak</td><td>65.30</td><td>{{ lp.4 }}</td><td>{{ ln.4 }}</td></tr>
                    <tr><td>1.&nbsp;Zee News</td><td>51.04</td><td>{{ lp.5 }}</td><td>{{ ln.5 }}</td></tr>
                    <tr><td>1.&nbsp;India Tv</td><td>0</td><td>{{ lp.6 }}</td><td>{{ ln.6 }}</td></tr>

                    <tr><td>1.&nbsp;Times of India</td><td>8.7</td><td>Star</td></tr>

                    <tr><td>1.&nbsp;Indian Express</td><td>8.7</td><td>Star</td></tr>
                    <tr><td>1.&nbsp;ABP News</td><td>8.7</td><td>Star</td></tr>


                </table>


        </div>



        </div>
        <div class="col l3">
           <div class="card">
               <p style="text-align:center;"><b>Sentiment Analysis</b></p>
               <table>
                   <tr><td><b>Positive</b></td><td>{{ positive }}</td></tr>
                   <tr><td><b>Negative</b></td><td>{{ negative }}</td></tr>
                   <tr><td>Stats</td><td>{{ percentage }}</td></tr>
                   <p></p>
               </table>

           </div>
        </div>
    </div>
{% endblock %}